### PR TITLE
Updated usage messages to specify protocol

### PR DESCRIPTION
**Pull request by Mrc0113**
Just some simple updates to make the samples more clear when running.

### CODE REVIEW

**Comment by mdspielman** [comment]
Marc, can you do this pull request from a branch. See Contributing.md for details.

**Review by mdspielman — APPROVED** [review]
These changes look reasonable. Thanks. We can merge once the PR is done from a branch.

**Review by mdspielman — CHANGES_REQUESTED** [review]
These changes look reasonable. Thanks. We can merge once the PR is done from a branch.

**Comment by Mrc0113** [comment]
It wouldn't let me change the branch you'd be pulling from so I created a new PR

**Pull request closed without merging**
